# Generated by Django 3.2.6 on 2021-09-03 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandterminals',
            name='brand',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='modelterminals',
            name='model',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='operatorssim',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='simcards',
            name='number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='simcards',
            name='sim_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='terminals',
            name='imei',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='terminals',
            name='serial_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modelterminals',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_terminal', to='general_app.brandterminals'),
        ),
        migrations.AlterField(
            model_name='simcards',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sim_operator', to='general_app.operatorssim'),
        ),
        migrations.AlterField(
            model_name='terminals',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_terminal', to='general_app.modelterminals'),
        ),
    ]
