# Generated by Django 3.2.6 on 2021-09-04 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0002_auto_20210903_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='simcards',
            name='terminal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terminal', to='general_app.modelterminals'),
        ),
        migrations.AlterField(
            model_name='modelterminals',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brand_terminal', to='general_app.brandterminals'),
        ),
        migrations.AlterField(
            model_name='simcards',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sim_operator', to='general_app.operatorssim'),
        ),
        migrations.AlterField(
            model_name='terminals',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='model_terminal', to='general_app.modelterminals'),
        ),
    ]
