# Generated by Django 3.2.6 on 2021-09-04 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0003_auto_20210904_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simcards',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operator', to='general_app.operatorssim'),
        ),
    ]
