# Generated by Django 3.2.6 on 2021-09-04 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0004_alter_simcards_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simcards',
            name='terminal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terminal', to='general_app.terminals'),
        ),
    ]
