# Generated by Django 3.2.6 on 2021-09-04 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0005_alter_simcards_terminal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandterminals',
            name='brand',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='modelterminals',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='t_brand', to='general_app.brandterminals'),
        ),
        migrations.AlterField(
            model_name='modelterminals',
            name='model',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='operatorssim',
            name='name',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='simcards',
            name='number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='simcards',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='s_operator', to='general_app.operatorssim'),
        ),
        migrations.AlterField(
            model_name='simcards',
            name='sim_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='simcards',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='s_terminal', to='general_app.terminals'),
        ),
        migrations.AlterField(
            model_name='terminals',
            name='imei',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='terminals',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='t_model', to='general_app.modelterminals'),
        ),
    ]
