# Generated by Django 3.2.6 on 2021-09-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0006_auto_20210904_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simcards',
            old_name='sim_id',
            new_name='icc',
        ),
        migrations.AlterField(
            model_name='terminals',
            name='imei',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
