# Generated by Django 3.2.6 on 2021-09-06 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0008_human_telegram_telephonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegram',
            name='number',
        ),
        migrations.AddField(
            model_name='telegram',
            name='human',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general_app.human'),
        ),
    ]
