# Generated by Django 3.2.6 on 2021-09-07 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0009_auto_20210906_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='WialonUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20, unique=True)),
                ('human', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='general_app.human')),
            ],
        ),
        migrations.CreateModel(
            name='WialonObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('terminal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='general_app.terminals')),
                ('wialon_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='general_app.wialonuser')),
            ],
        ),
    ]
