# Generated by Django 3.2.6 on 2021-09-08 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0011_wialonobjectactive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terminals',
            options={'ordering': ['imei']},
        ),
    ]
