# Generated by Django 3.2.6 on 2021-09-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0012_alter_terminals_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='wialonobjectactive',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
