# Generated by Django 3.2.6 on 2021-09-13 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0013_wialonobjectactive_last_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandterminals',
            options={'ordering': ['brand']},
        ),
        migrations.AlterModelOptions(
            name='modelterminals',
            options={'ordering': ['model']},
        ),
        migrations.AlterModelOptions(
            name='simcards',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='wialonobject',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='wialonobjectactive',
            options={'ordering': ['wialon_object']},
        ),
        migrations.AlterModelOptions(
            name='wialonuser',
            options={'ordering': ['user_name']},
        ),
        migrations.AlterField(
            model_name='terminals',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='t_model', to='general_app.modelterminals'),
        ),
        migrations.AlterField(
            model_name='wialonuser',
            name='human',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='general_app.human'),
        ),
    ]
