# Generated by Django 3.2.6 on 2021-09-13 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0014_auto_20210913_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='WialonServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserWialonServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='general_app.wialonserver')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='general_app.wialonuser')),
            ],
        ),
    ]
