# Generated by Django 3.2.6 on 2021-09-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0015_userwialonserver_wialonserver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wialonuser',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
