# Generated by Django 3.2.6 on 2021-09-15 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0016_alter_wialonuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanTerminalPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general_app.human')),
                ('terminal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='general_app.terminals')),
            ],
        ),
    ]
