# Generated by Django 3.2.6 on 2021-09-15 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0017_humanterminalpresence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='human',
            options={'ordering': ['first_name']},
        ),
        migrations.CreateModel(
            name='HumanSimPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general_app.human')),
                ('simcard', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='general_app.simcards')),
            ],
        ),
    ]
