# Generated by Django 3.2.6 on 2021-09-15 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0018_auto_20210915_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humansimpresence',
            options={'ordering': ['human']},
        ),
        migrations.AlterModelOptions(
            name='humanterminalpresence',
            options={'ordering': ['human']},
        ),
    ]
