# Generated by Django 3.2.6 on 2021-09-19 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0019_auto_20210915_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wialonobjectactive',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
