# Generated by Django 3.2.6 on 2021-10-08 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0020_alter_wialonobjectactive_last_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='telegram',
            name='human',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='general_app.human'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general_app.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general_app.wialonuser')),
            ],
            options={
                'verbose_name': 'Юзер+Компания',
            },
        ),
        migrations.CreateModel(
            name='HumanCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general_app.company', verbose_name='Компания')),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general_app.human', verbose_name='Человек')),
            ],
            options={
                'verbose_name': 'Человек+Компания',
            },
        ),
    ]
