# Generated by Django 3.2.6 on 2021-10-08 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0021_auto_20211008_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humancompany',
            options={'verbose_name': 'Компания + Человек', 'verbose_name_plural': 'Компании + Люди'},
        ),
        migrations.AlterModelOptions(
            name='usercompany',
            options={'verbose_name': 'Компания + Юзер', 'verbose_name_plural': 'Компании + Юзеры'},
        ),
    ]
