# Generated by Django 3.2.6 on 2021-10-11 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0022_auto_20211008_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HumanContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_rec', models.CharField(max_length=45)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_app.contact')),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_app.human')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='record',
            field=models.ManyToManyField(through='general_app.HumanContact', to='general_app.Human'),
        ),
    ]
