# Generated by Django 3.2.6 on 2021-10-11 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0023_auto_20211011_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humancontact',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterField(
            model_name='humancontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_app.contact', verbose_name='Версия контакта'),
        ),
        migrations.AlterField(
            model_name='humancontact',
            name='contact_rec',
            field=models.CharField(max_length=45, verbose_name='Запись'),
        ),
        migrations.AlterField(
            model_name='humancontact',
            name='human',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_app.human', verbose_name='Человек'),
        ),
    ]
