# Generated by Django 3.2.6 on 2021-10-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0024_auto_20211011_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='human_company',
            field=models.ManyToManyField(through='general_app.HumanCompany', to='general_app.Human'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=45, verbose_name='Название'),
        ),
    ]
