# Generated by Django 3.2.6 on 2021-10-12 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0025_auto_20211011_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='humancompany',
            old_name='company',
            new_name='company_hum',
        ),
        migrations.RenameField(
            model_name='humancompany',
            old_name='human',
            new_name='human_comp',
        ),
        migrations.RenameField(
            model_name='usercompany',
            old_name='company',
            new_name='company_us',
        ),
        migrations.RenameField(
            model_name='usercompany',
            old_name='user',
            new_name='user_comp',
        ),
    ]
