# Generated by Django 3.2.6 on 2021-10-12 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0026_auto_20211012_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompany',
            name='company_us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general_app.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='user_comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general_app.wialonuser', verbose_name='Юзер'),
        ),
    ]
