# Generated by Django 3.2.6 on 2021-10-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0027_auto_20211012_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wialonobject',
            name='name',
            field=models.CharField(max_length=45),
        ),
    ]
