# Generated by Django 3.2.6 on 2021-10-22 20:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0028_alter_wialonobject_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humansimpresence',
            options={'ordering': ['human'], 'verbose_name': 'Человек + Симка', 'verbose_name_plural': 'Люди + Симки'},
        ),
        migrations.AlterModelOptions(
            name='humanterminalpresence',
            options={'ordering': ['human'], 'verbose_name': 'Человек + Терминал', 'verbose_name_plural': 'Люди + Терминалы'},
        ),
        migrations.AddField(
            model_name='simcards',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terminals',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wialonobject',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelterminals',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='models', to='general_app.brandterminals'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='simcards',
            name='number',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
