# Generated by Django 3.2.6 on 2021-11-03 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0029_auto_20211022_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wialonobject',
            name='terminal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wialonobjects', to='general_app.terminals'),
        ),
        migrations.AlterField(
            model_name='wialonobject',
            name='wialon_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wialonobjects', to='general_app.wialonuser'),
        ),
    ]
