# Generated by Django 3.2.6 on 2021-11-03 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0030_auto_20211103_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humansimpresence',
            name='human',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='humansimpresences', to='general_app.human'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='humansimpresence',
            name='simcard',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='humansimpresences', to='general_app.simcards'),
        ),
    ]
