# Generated by Django 3.2.6 on 2021-12-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0031_auto_20211103_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminals',
            name='serial_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
