# Generated by Django 3.2.6 on 2022-05-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0032_alter_terminals_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='humansimpresence',
            name='time_create',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='humanterminalpresence',
            name='time_create',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
