# Generated by Django 3.2.6 on 2022-09-22 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0033_auto_20220519_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandterminals',
            options={'ordering': ['brand'], 'verbose_name': 'Марка терминала', 'verbose_name_plural': 'Марки терминалов'},
        ),
        migrations.AlterModelOptions(
            name='modelterminals',
            options={'ordering': ['model'], 'verbose_name': 'Модель терминала', 'verbose_name_plural': 'Модели терминалов'},
        ),
        migrations.AlterModelOptions(
            name='simcards',
            options={'ordering': ['number'], 'verbose_name': 'Сим-карта', 'verbose_name_plural': 'Сим-карты'},
        ),
        migrations.AlterModelOptions(
            name='terminals',
            options={'ordering': ['imei'], 'verbose_name': 'Терминал', 'verbose_name_plural': 'Терминалы'},
        ),
    ]
