# Generated by Django 3.2.6 on 2022-09-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0035_brandcar_installation_modelcar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Комментарий'),
        ),
    ]
