# Generated by Django 3.2.6 on 2022-09-27 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0036_alter_installation_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installation',
            name='brand',
        ),
    ]
