# Generated by Django 3.2.6 on 2022-09-27 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0037_remove_installation_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='installations', to='general_app.modelcar', verbose_name='Модель ТС'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='state_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Гос. номер'),
        ),
        migrations.AlterField(
            model_name='modelcar',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название Модели'),
        ),
    ]
