# Generated by Django 3.2.6 on 2022-09-28 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0038_auto_20220927_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humansimpresence',
            options={'ordering': ['human'], 'verbose_name': 'Человек + SIM-карта', 'verbose_name_plural': 'Люди + SIM-карты'},
        ),
        migrations.AlterModelOptions(
            name='simcards',
            options={'ordering': ['number'], 'verbose_name': 'SIM-карта', 'verbose_name_plural': 'SIM-карты'},
        ),
        migrations.AlterModelOptions(
            name='userwialonserver',
            options={'ordering': ['user'], 'verbose_name': 'Пользователь + Сервер', 'verbose_name_plural': 'Пользователи + Серверы'},
        ),
        migrations.AlterModelOptions(
            name='wialonserver',
            options={'ordering': ['name'], 'verbose_name': 'Сервер', 'verbose_name_plural': 'Серверы'},
        ),
        migrations.AlterField(
            model_name='humansimpresence',
            name='human',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='humansimpresences', to='general_app.human', verbose_name='Человек'),
        ),
        migrations.AlterField(
            model_name='humansimpresence',
            name='simcard',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='humansimpresences', to='general_app.simcards', verbose_name='SIM-карта'),
        ),
        migrations.AlterField(
            model_name='humansimpresence',
            name='time_create',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='humanterminalpresence',
            name='human',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='humanterminalpresences', to='general_app.human', verbose_name='Человек'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='humanterminalpresence',
            name='terminal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='general_app.terminals', verbose_name='Терминал'),
        ),
        migrations.AlterField(
            model_name='humanterminalpresence',
            name='time_create',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='simcards',
            name='icc',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='ICC'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='simcards',
            name='number',
            field=models.CharField(default=1, max_length=16, unique=True, verbose_name='Номер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='simcards',
            name='operator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='s_operator', to='general_app.operatorssim'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='simcards',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='s_terminal', to='general_app.terminals', verbose_name='Терминал'),
        ),
        migrations.AlterField(
            model_name='simcards',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='userwialonserver',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='userwialonservers', to='general_app.wialonserver', verbose_name='Сервер'),
        ),
        migrations.AlterField(
            model_name='userwialonserver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='general_app.wialonuser', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='wialonserver',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Сервер'),
        ),
    ]
