# Generated by Django 3.2.6 on 2022-09-28 07:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0039_auto_20220928_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name'], 'verbose_name': 'Вариант контакта', 'verbose_name_plural': 'Варианты контактов'},
        ),
        migrations.AlterModelOptions(
            name='human',
            options={'ordering': ['first_name'], 'verbose_name': 'Человек', 'verbose_name_plural': 'Люди'},
        ),
        migrations.AlterModelOptions(
            name='operatorssim',
            options={'ordering': ['name'], 'verbose_name': 'Оператор', 'verbose_name_plural': 'Операторы'},
        ),
        migrations.AlterModelOptions(
            name='usercompany',
            options={'verbose_name': 'Компания + Пользователь', 'verbose_name_plural': 'Компании + Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='wialonobject',
            options={'ordering': ['name'], 'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
        migrations.AlterModelOptions(
            name='wialonobjectactive',
            options={'ordering': ['wialon_object'], 'verbose_name': 'Объект + Статус', 'verbose_name_plural': 'Объекты + Статусы'},
        ),
        migrations.AlterModelOptions(
            name='wialonuser',
            options={'ordering': ['user_name'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='brandterminals',
            name='brand',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='company',
            name='human_company',
            field=models.ManyToManyField(through='general_app.HumanCompany', to='general_app.Human', verbose_name='Человек'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=45, verbose_name='Название контакта'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='record',
            field=models.ManyToManyField(through='general_app.HumanContact', to='general_app.Human', verbose_name='Человек'),
        ),
        migrations.AlterField(
            model_name='human',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='human',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='modelterminals',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='general_app.brandterminals', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='modelterminals',
            name='model',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='operatorssim',
            name='name',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='simcards',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='s_operator', to='general_app.operatorssim', verbose_name='Оператор'),
        ),
        migrations.AlterField(
            model_name='terminals',
            name='imei',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='IMEI'),
        ),
        migrations.AlterField(
            model_name='terminals',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='t_model', to='general_app.modelterminals', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='terminals',
            name='serial_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='terminals',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='user_comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general_app.wialonuser', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='wialonobject',
            name='terminal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wialonobjects', to='general_app.terminals', verbose_name='Терминал'),
        ),
        migrations.AlterField(
            model_name='wialonobject',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='wialonobject',
            name='wialon_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wialonobjects', to='general_app.wialonuser', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='wialonobjectactive',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='wialonobjectactive',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='wialonobjectactive',
            name='wialon_object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='general_app.wialonobject', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='wialonuser',
            name='human',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='general_app.human', verbose_name='Человек'),
        ),
        migrations.AlterField(
            model_name='wialonuser',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='wialonuser',
            name='user_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Пользователь'),
        ),
    ]
