# Generated by Django 3.2.6 on 2022-09-28 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0040_auto_20220928_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelcar',
            options={'ordering': ['brand'], 'verbose_name': 'Модель ТС', 'verbose_name_plural': 'Модели ТС'},
        ),
        migrations.RemoveField(
            model_name='installation',
            name='comment',
        ),
        migrations.CreateModel(
            name='InstallationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
                ('installation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='installationcomments', to='general_app.installation', verbose_name='Установка')),
            ],
            options={
                'verbose_name': 'Установки + комментарии',
                'ordering': ['installation'],
            },
        ),
    ]
