# Generated by Django 3.2.6 on 2022-09-28 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0041_auto_20220928_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installationcomment',
            options={'ordering': ['installation'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Установки + Комментарии'},
        ),
    ]
