# Generated by Django 3.2.6 on 2022-10-04 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0042_alter_installationcomment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wialonobject',
            name='terminal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wialonobjects', to='general_app.terminals', verbose_name='Терминал'),
        ),
    ]
