# Generated by Django 3.2.6 on 2023-08-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0043_alter_wialonobject_terminal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wialonuser',
            name='user_name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='wialonobject',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='wialonobject',
            name='price',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='wialonuser',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='wialonuser',
            name='payment',
            field=models.BooleanField(default=False, verbose_name='Оплата'),
        ),
    ]
