# Generated by Django 3.2.6 on 2023-12-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0044_alter_wialonuser_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='comment',
            field=models.CharField(default=0, max_length=255, verbose_name='Комментарий'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installation',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='VIN'),
        ),
    ]
