# Generated by Django 3.2.6 on 2023-12-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0045_auto_20231202_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='simcards',
            name='number',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='simcards',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='wialonobject',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
