# Generated by Django 4.2.16 on 2024-09-18 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0046_alter_installation_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='wialonobject',
            name='payer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='payer_human', to='general_app.human', verbose_name='Плательщик'),
            preserve_default=False,
        ),
    ]
