# Generated by Django 4.2.16 on 2024-09-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0047_wialonobject_date_payment_wialonobject_payer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wialonobject',
            name='name',
            field=models.CharField(max_length=45, verbose_name='Имя'),
        ),
    ]
