# Generated by Django 4.2.16 on 2024-09-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0048_alter_wialonobject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='juristic_person',
            field=models.BooleanField(default=0, verbose_name='Юр-лицо'),
            preserve_default=False,
        ),
    ]
