# Generated by Django 4.2.16 on 2024-10-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0049_installation_juristic_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='wialonobject',
            name='active',
            field=models.BooleanField(default=0, verbose_name='Статус'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wialonobject',
            name='date_change_status',
            field=models.DateField(auto_now_add=True, default='2020-01-01', verbose_name='Дата изменения статуса'),
            preserve_default=False,
        ),
    ]
