# Generated by Django 4.2.16 on 2024-10-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0050_wialonobject_active_wialonobject_date_change_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wialonobject',
            name='time_create',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
    ]
