# Generated by Django 4.2.16 on 2024-10-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0051_alter_wialonobject_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wialonobject',
            name='date_change_status',
            field=models.DateField(verbose_name='Дата изменения статуса'),
        ),
        migrations.AlterField(
            model_name='wialonobject',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
