# Generated by Django 4.2.16 on 2024-10-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0052_alter_wialonobject_date_change_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Имя',
                'verbose_name_plural': 'Имена',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='human',
            options={'ordering': ['last_name'], 'verbose_name': 'Человек', 'verbose_name_plural': 'Люди'},
        ),
        migrations.AddField(
            model_name='human',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Описание'),
        ),
    ]
