# Generated by Django 4.2.16 on 2024-10-03 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0053_humannames_alter_human_options_human_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandcar',
            options={'ordering': ['name'], 'verbose_name': 'Марка ТС', 'verbose_name_plural': 'ТС: марки'},
        ),
        migrations.AlterModelOptions(
            name='brandterminals',
            options={'ordering': ['brand'], 'verbose_name': 'Марка терминала', 'verbose_name_plural': 'Терминал: марки'},
        ),
        migrations.AlterModelOptions(
            name='modelcar',
            options={'ordering': ['brand'], 'verbose_name': 'Модель ТС', 'verbose_name_plural': 'ТС: модели'},
        ),
        migrations.AlterModelOptions(
            name='modelterminals',
            options={'ordering': ['model'], 'verbose_name': 'Модель терминала', 'verbose_name_plural': 'Терминал: модели'},
        ),
        migrations.AlterModelOptions(
            name='userwialonserver',
            options={'ordering': ['user'], 'verbose_name': 'Сервер + Пользователь', 'verbose_name_plural': 'Серверы + Пользователи'},
        ),
        migrations.AlterField(
            model_name='modelcar',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelcars', to='general_app.brandcar', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='modelcar',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Модель'),
        ),
    ]
