# Generated by Django 4.2.16 on 2024-10-04 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0054_alter_brandcar_options_alter_brandterminals_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='name_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='general_app.humannames', verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
