# Generated by Django 4.2.16 on 2024-10-04 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0055_human_name_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='human',
            options={'ordering': ['name_id', 'last_name'], 'verbose_name': 'Человек', 'verbose_name_plural': 'Люди'},
        ),
        migrations.RemoveField(
            model_name='human',
            name='first_name',
        ),
    ]
