# Generated by Django 4.2.16 on 2024-10-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0056_alter_human_options_remove_human_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wialonuser',
            name='password',
        ),
    ]
