# Generated by Django 4.2.16 on 2024-10-05 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0057_remove_wialonuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarGenerations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.CharField(max_length=128, verbose_name='Поколение')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='Описание')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general_app.modelcar', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Поколение ТС',
                'verbose_name_plural': 'ТС: поколения',
                'ordering': ['model_id'],
            },
        ),
    ]
