# Generated by Django 4.2.16 on 2024-10-07 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0058_cargenerations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wialonuser',
            options={'ordering': ['user_name'], 'verbose_name': 'Учётная запись', 'verbose_name_plural': 'Учётные записи'},
        ),
        migrations.RemoveField(
            model_name='wialonuser',
            name='payment',
        ),
        migrations.AddField(
            model_name='wialonuser',
            name='server',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='general_app.wialonserver', verbose_name='Сервер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wialonobject',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='wialonobject',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='wialonobject',
            name='price',
            field=models.PositiveBigIntegerField(default=1, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='wialonobject',
            name='wialon_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='wialonobjects', to='general_app.wialonuser', verbose_name='Учётная запись'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wialonuser',
            name='user_name',
            field=models.CharField(max_length=255, verbose_name='Учётная запись'),
        ),
    ]
