# Generated by Django 4.2.16 on 2024-10-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0059_alter_wialonuser_options_remove_wialonuser_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wialonobject',
            name='date_change_status',
            field=models.DateField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
    ]
