# Generated by Django 4.2.16 on 2024-10-14 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0060_alter_wialonobject_date_change_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='payer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='general_app.human', verbose_name='Плательщик'),
            preserve_default=False,
        ),
    ]
