# Generated by Django 4.2.16 on 2024-10-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0061_installation_payer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wialonobject',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Нужность'),
        ),
    ]
