# Generated by Django 4.2.16 on 2024-10-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0062_alter_wialonobject_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humancontact',
            name='contact_rec',
            field=models.CharField(max_length=255, verbose_name='Запись'),
        ),
    ]
