# Generated by Django 4.2.16 on 2024-11-06 05:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0063_alter_humancontact_contact_rec'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий')),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general_app.human', verbose_name='Человек')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'График',
                'ordering': ['-date'],
            },
        ),
    ]
