# Generated by Django 4.2.16 on 2025-01-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0064_schedules'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceLogistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Пункт')),
                ('cost', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Выезд',
                'verbose_name_plural': 'Цена выездов',
                'ordering': ['city'],
            },
        ),
    ]
