# Generated by Django 4.2.16 on 2025-01-09 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0065_pricelogistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Серийный номер')),
                ('add_information', models.CharField(blank=True, max_length=255, null=True, verbose_name='Доп.инфо')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий')),
                ('time_create', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general_app.modelterminals', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Датчик',
                'verbose_name_plural': 'Датчики',
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='HumanSensorRelations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий')),
                ('time_create', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general_app.human', verbose_name='Человек')),
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='general_app.sensors', verbose_name='Датчик')),
            ],
            options={
                'verbose_name': 'Человек + Датчик',
                'verbose_name_plural': 'Люди + Датчики',
                'ordering': ['human'],
            },
        ),
    ]
