# Generated by Django 4.2.16 on 2025-01-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0066_sensors_humansensorrelations'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminals',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Действующий'),
        ),
    ]
