# Generated by Django 4.2.16 on 2025-01-24 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0067_terminals_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricelogistics',
            options={'ordering': ['city'], 'verbose_name': 'Выезд', 'verbose_name_plural': 'Прайс.Выезды'},
        ),
        migrations.AddField(
            model_name='pricelogistics',
            name='last_modified',
            field=models.DateField(auto_now=True, verbose_name='Посл. изменения'),
        ),
        migrations.CreateModel(
            name='PriceTrackers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий')),
                ('last_modified', models.DateField(auto_now=True, verbose_name='Посл. изменения')),
                ('tracker_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general_app.modelterminals', verbose_name='Модель трекера')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Прайс.Трекеры',
                'ordering': ['cost'],
            },
        ),
    ]
