# Generated by Django 4.2.16 on 2025-01-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0068_alter_pricelogistics_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=255, verbose_name='Услуга')),
                ('cost', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('ordering', models.SmallIntegerField(blank=True, null=True, verbose_name='Очерёдность')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий')),
                ('last_modified', models.DateField(auto_now=True, verbose_name='Посл. изменения')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['ordering'],
            },
        ),
        migrations.AlterModelOptions(
            name='pricetrackers',
            options={'ordering': ['cost'], 'verbose_name': 'Цена', 'verbose_name_plural': 'Прайс.Оборудование'},
        ),
    ]
