# Generated by Django 4.2.16 on 2025-04-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0069_services_alter_pricetrackers_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['ordering', 'service'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='simcards',
            name='personal',
            field=models.BooleanField(default=False, verbose_name='Личная'),
        ),
    ]
