# Generated by Django 4.2.16 on 2025-05-17 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0070_alter_services_options_simcards_personal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humancompany',
            name='company_hum',
        ),
        migrations.RemoveField(
            model_name='humancompany',
            name='human_comp',
        ),
        migrations.RemoveField(
            model_name='installationcomment',
            name='installation',
        ),
        migrations.RemoveField(
            model_name='telegram',
            name='human',
        ),
        migrations.RemoveField(
            model_name='telephonenumber',
            name='human',
        ),
        migrations.RemoveField(
            model_name='usercompany',
            name='company_us',
        ),
        migrations.RemoveField(
            model_name='usercompany',
            name='user_comp',
        ),
        migrations.RemoveField(
            model_name='wialonobjectactive',
            name='wialon_object',
        ),
        migrations.AlterField(
            model_name='cargenerations',
            name='model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_car_generations', to='general_app.modelcar', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='human',
            name='name_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='name_humans', to='general_app.humannames', verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='humansensorrelations',
            name='human',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='human_sensor_holders', to='general_app.human', verbose_name='Человек'),
        ),
        migrations.AlterField(
            model_name='humansensorrelations',
            name='sensor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sensor_holders', to='general_app.sensors', verbose_name='Датчик'),
        ),
        migrations.AlterField(
            model_name='humansimpresence',
            name='human',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='human_sim_card_holders', to='general_app.human', verbose_name='Человек'),
        ),
        migrations.AlterField(
            model_name='humansimpresence',
            name='simcard',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sim_card_holders', to='general_app.simcards', verbose_name='SIM-карта'),
        ),
        migrations.AlterField(
            model_name='humanterminalpresence',
            name='human',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='human_terminal_holders', to='general_app.human', verbose_name='Человек'),
        ),
        migrations.AlterField(
            model_name='humanterminalpresence',
            name='terminal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='terminal_holders', to='general_app.terminals', verbose_name='Терминал'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='human_worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='human_worker_installations', to='general_app.human', verbose_name='Установщик'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='model_installations', to='general_app.modelcar', verbose_name='Модель ТС'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payer_installations', to='general_app.human', verbose_name='Плательщик'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminal_installations', to='general_app.terminals', verbose_name='Терминал'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_installations', to='general_app.wialonuser', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='modelcar',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brand_car_models', to='general_app.brandcar', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='modelterminals',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brand_models', to='general_app.brandterminals', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='pricetrackers',
            name='tracker_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_tracker_prices', to='general_app.modelterminals', verbose_name='Модель трекера'),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='human',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='human_schedules', to='general_app.human', verbose_name='Человек'),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_sensors', to='general_app.modelterminals', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='simcards',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operator_sim_cards', to='general_app.operatorssim', verbose_name='Оператор'),
        ),
        migrations.AlterField(
            model_name='simcards',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terminal_sim_cards', to='general_app.terminals', verbose_name='Терминал'),
        ),
        migrations.AlterField(
            model_name='terminals',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='model_terminals', to='general_app.modelterminals', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='wialonobject',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payer_glonass_objects', to='general_app.human', verbose_name='Плательщик'),
        ),
        migrations.AlterField(
            model_name='wialonobject',
            name='terminal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terminal_glonass_objects', to='general_app.terminals', verbose_name='Терминал'),
        ),
        migrations.AlterField(
            model_name='wialonobject',
            name='wialon_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_glonass_objects', to='general_app.wialonuser', verbose_name='Учётная запись'),
        ),
        migrations.AlterField(
            model_name='wialonuser',
            name='human',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='human_glonass_users', to='general_app.human', verbose_name='Человек'),
        ),
        migrations.AlterField(
            model_name='wialonuser',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='server_glonass_users', to='general_app.wialonserver', verbose_name='Сервер'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='HumanCompany',
        ),
        migrations.DeleteModel(
            name='InstallationComment',
        ),
        migrations.DeleteModel(
            name='Telegram',
        ),
        migrations.DeleteModel(
            name='TelephoneNumber',
        ),
        migrations.DeleteModel(
            name='UserCompany',
        ),
        migrations.DeleteModel(
            name='WialonObjectActive',
        ),
    ]
