# Generated by Django 4.2.16 on 2025-05-18 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0071_remove_humancompany_company_hum_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandterminals',
            options={'verbose_name': 'Марка терминала', 'verbose_name_plural': 'Терминал: марки'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Вариант контакта', 'verbose_name_plural': 'Варианты контактов'},
        ),
        migrations.AlterModelOptions(
            name='humansensorrelations',
            options={'verbose_name': 'Человек + Датчик', 'verbose_name_plural': 'Люди + Датчики'},
        ),
        migrations.AlterModelOptions(
            name='humansimpresence',
            options={'verbose_name': 'Держатель SIM-карты', 'verbose_name_plural': 'Держатели SIM-карт'},
        ),
        migrations.AlterModelOptions(
            name='humanterminalpresence',
            options={'verbose_name': 'Человек + Терминал', 'verbose_name_plural': 'Люди + Терминалы'},
        ),
        migrations.AlterModelOptions(
            name='modelterminals',
            options={'verbose_name': 'Модель терминала', 'verbose_name_plural': 'Терминал: модели'},
        ),
        migrations.AlterModelOptions(
            name='operatorssim',
            options={'verbose_name': 'Оператор', 'verbose_name_plural': 'Операторы'},
        ),
        migrations.AlterModelOptions(
            name='simcards',
            options={'verbose_name': 'SIM-карта', 'verbose_name_plural': 'SIM-карты'},
        ),
        migrations.AlterModelOptions(
            name='terminals',
            options={'verbose_name': 'Терминал', 'verbose_name_plural': 'Терминалы'},
        ),
        migrations.RemoveField(
            model_name='simcards',
            name='personal',
        ),
        migrations.AddField(
            model_name='humansimpresence',
            name='personal',
            field=models.BooleanField(default=False, verbose_name='Личная'),
        ),
        migrations.AlterField(
            model_name='humansimpresence',
            name='human',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='human_sim_card_holders', to='general_app.human', verbose_name='Держатель'),
        ),
    ]
